encoding: utf-8
lang: ja
timezone: Asia/Tokyo

plugins: ["jekyll-remote-theme", "jekyll-feed", "jekyll-sitemap"]
remote_theme: ress997/jekyll-lime

url: https://profile.jp.net
title: ProfileJP
description: ""
copyright: 2023 ProfileJP
